### ISSUE TITLE
How to download licenses.json file？

### ISSUE THREAD

**Issue by nzk1912** [pyupio/safety#335]
as the title~

**Comment by dylanpulver** [comment]
Hi @nzk1912,

Thank you for your question about downloading the licenses.json file.

It appears that this issue is more of a question than a bug or feature request. To help you better, could you please provide more details on what you are trying to achieve? 

We'd love to assist you further once we have more information. Please feel free to update this issue with additional details, and we'll do our best to help. We will move the issue to the wontfix column.

Thank you for your understanding and for reaching out!

Best regards,

The Safety Team
