### ISSUE TITLE
Is Safety 3 still beta?

### ISSUE THREAD

**Issue by Zeckie** [pyupio/safety#532]
https://safetycli.com/research/safety-cli-3-vulnerability-scanning-for-secure-python-development (and various other pages such as https://docs.safetycli.com/safety-docs/safety-cli-3/available-commands-and-inputs) seem to say that Safety 3.0 has been released, and safety 2.x has been deprecated. However, there are some references in the documentation that seem to imply that safety 2.x is the current version, and 3.x is still beta. 

https://docs.safetycli.com/safety-docs/safety-cli-3/system-wide-developer-machine-scanning

> Please note that the new `safety scan` command is currently in beta. At this time, `safety check` is still supported but will be phased out in the coming months as we transition fully to `safety scan`.

https://docs.safetycli.com/safety-2

> Existing Customers: Upgrade to Safety 3.0
> 
> Safety 3.0 is now available, providing system-wide scanning, unpinned package support, new SBOM and JSON output formats, and more. 
> 
> To join the beta for the Safety 3.0 release, please complete this form.

**Comment by mwermuth** [comment]
Hey there @Zeckie,
thanks for sharing and asking that question. I am sorry that some of the docs are a bit confusing around our new version. I've created an issue for us internally to fix it as soon as we can.

The answer: No Safety 3 and `safety scan` are not in beta anymore. `safety scan` is our all new command and which everyone should use going forward. 

Does this help you?

I'll follow up on this issue here once we fix our docs 🙌
